In [1]:
import tkinter as tk
from PIL import Image as PILImage
from PIL import ImageTk
from tkinter import Label
from tkinter import filedialog
from tkinter import ttk
from tkinter import Menu 
import cv2
import matplotlib.pyplot as plt
import numpy as np

effectoption = ["Effect0",
"Effect1",
"Effect2",
"Effect3", "Effect4"]

effectoption2 = ["Original(RGB)",
"Original(HSV)",
"Effect3"]

global image, edited

def insertbutton_cb():
    global orima, editima
    
    picpath = filedialog.askopenfilename(
        title="Select An Image", 
        filetypes=(("JPG Files", "*.jpg"), ("GIF Files", "*.gif*"), ("PNG files", "*.png"), ("JPEG Files", "*.jpeg"))
    )
    
    if len(picpath) > 0:
        
        image = cv2.imread(picpath)
        edited = cv2.imread(picpath)
        
        edited = np.array(edited)
        
        print(picpath)
        print('Original Dimensions : ',image.shape)
        print(image)
        print(edited)
        
        scale_percent = 50 # percent of original size
        width = int(image.shape[1] * scale_percent / 100)
        height = int(image.shape[0] * scale_percent / 100)
        width2 = int(edited.shape[1] * scale_percent / 100)
        height2 = int(edited.shape[0] * scale_percent / 100)
        dim = (width, height)
        dim2 = (width2, height2)
        
        image = cv2.resize(image, dim, interpolation = cv2.INTER_AREA)
        edited = cv2.resize(edited, dim2, interpolation = cv2.INTER_AREA)
        
        if effectoption[0] :
            edited = cv2.cvtColor(edited, cv2.COLOR_BGR2RGB)
        elif effectoption[1] :
            edited = cv2.cvtColor(edited, cv2.COLOR_BGR2HSV)
        elif effectoption[2] :
            edited = cv2.cvtColor(edited, cv2.COLOR_BGR2LAB)
        elif effectoption[3] :
            edited = cv2.cvtColor(edited, cv2.COLOR_BGR2RGBA)
        
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        edited = cv2.cvtColor(edited, cv2.COLOR_BGR2RGB)
        
        image =  PILImage.fromarray(image)
        edited = PILImage.fromarray(edited)
        
        image = np.uint8(image)
        edited = np.uint8(edited)
        
        
        opt = tk.OptionMenu(window, var1, *effectoption)
        opt.config(width=90, font=('Helvetica', 12))
        opt.pack(side="top")
        
        #hueSlider = tk.Scale(Frm2, label="Hue",from_=0, to=100, orient=tk.HORIZONTAL, length=sw, resolution=1, command=huecb)
        #hueSlider.pack(anchor=tk.N)

        #saturationSlider = tk.Scale(Frm2, label="Saturation",from_=0, to=100, orient=tk.HORIZONTAL, length=sw, resolution=1, command=satcb)
        #saturationSlider.pack(anchor=tk.N)

        #brightSlider = tk.Scale(Frm2, label="Brightness",from_=0, to=100, orient=tk.HORIZONTAL, length=sw, resolution=1, command=brightcb)
        #brightSlider.pack(anchor=tk.N)

        #contrastSlider = tk.Scale(Frm2, label="Contrast",from_=0, to=100, orient=tk.HORIZONTAL, length=sw, resolution=1, command=contrastcb)
        #contrastSlider.pack(anchor=tk.N)
        
        bright = 255
        contrast = 100
        saturation = 50
        
        cv2.namedWindow('CV2 Photo Editor')   
        cv2.createTrackbar('Bright', 'CV2 Photo Editor', 255, 2 * 255, bccb)
        cv2.createTrackbar('Contrast', 'CV2 Photo Editor', 255, 2 * 127, bccb)
        cv2.createTrackbar('Saturation', 'CV2 Photo Editor', 255, 2 * 255, bccb) 
        functionbcs(edited, 0, 0, 0)
        bccb(0, 0, 0)
        teste = controller(edited, bright, contrast, saturation)
        cv2.imshow('CV2 Photo Editor', teste)
    
        #cv2.waitKey(0)
        
    if orima is None or editima is None:
        orima = Label(image=image)
        orima.image = image
        orima.pack(side="left", padx= 0, pady=0)
        
        editima = Label(image=edited)
        editima.image = edited
        editima.pack(side="right", padx= 0, pady=0)
    else:
        orima.configure(image=image)
        editima.configure(image=edited)
        orima.image = image
        editima.image = edited
    #filenm = filedialog.askopenfilename(
    #filetypes=[("Image File", "*.jpg"),("All Files","*.*")],
                        #title = "Choose a file.")
    #orima = Image.open(filenm)
    #editima = Image.open(filenm)
    
    #orimage = numpy.array(orima)
    #editimage = numpy.array(editima)
    
    #cv2.imshow(orimage)

    #orimage = cv2.resize(orima, (0, 0), None, .25, .25)
    #editmage = cv2.resize(editima, (0, 0), None, .25, .25)
    
    #scale_percent = 60 # percent of original size
    #width = int(img.shape[1] * scale_percent / 100)
    #height = int(img.shape[0] * scale_percent / 100)
    #dim = (width, height)
  
    # resize image
    #resized = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)

def resetbutton_cb():
    pass

def savebutton_cb():
    pass

def functionbcs(edited, bright=0, contrast=0, saturation=0):
        
    #edited = cv2.cvtColor(edited, cv2.COLOR_BGR2RGB)
    bright = cv2.getTrackbarPos('Bright','CV2 Photo Editor')
    contrast = cv2.getTrackbarPos('Contrast','CV2 Photo Editor')
    saturation = cv2.getTrackbarPos('Saturation','CV2 Photo Editor')
    effect = controller(edited, bright, contrast, saturation)
    #print("Edited : " + edited)
    print(effect)
    cv2.imshow("Edited", effect)

def satcb(satpos = 0):
    print(satpos)

def bccb(bright = 0, contrast=0, saturation=0):
    print(bright)
    bright = cv2.getTrackbarPos('Bright','CV2 Photo Editor')
    print(contrast)
    contrast = cv2.getTrackbarPos('Contrast','CV2 Photo Editor')
    print(saturation)
    saturation = cv2.getTrackbarPos('Saturation','CV2 Photo Editor')
    
    
def controller(effect, bright, contrast, saturation):
    bright = int((bright - 0) * (255 - (-255)) / (510 - 0) + (-255))
  
    contrast = int((contrast - 0) * (127 - (-127)) / (254 - 0) + (-127))
    
    saturation = int((saturation - 0) * (100 - (-100)) / (200 - 0) + (-100))
    
    if bright != 0:
        if bright > 0:
            shadow = bright
            max = 255
        else:
            shadow = 0
            max = 255 + brightness
        alf = (max - shadow) / 255
        gam = shadow
        
        cal = cv2.addWeighted(edited, alfa, 
                              edited, 0, gam)
    else:
        cal = effect
    
    if contrast != 0:
        Alf2 = float(131 * (contrast + 127)) / (127 * (131 - contrast))
        Gam2 = 127 * (1 - Alf2)
  
        # The function addWeighted calculates
        # the weighted sum of two arrays
        cal = cv2.addWeighted(cal, Alf2,
                              cal, 0, Gam2)
    cv2.putText(cal, 'B:{},C:{}, S:{}'.format(bright,
                                        contrast, saturation), (10, 30),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
    
    
        
    return cal

def exitbutton_cb():
    window.destroy()
    

window = tk.Tk()
window.title('Simple Photo Editing')
mb = Menu(window)
#file manager
fm = Menu(mb, tearoff=0)
fm.add_command(label="Open", command=insertbutton_cb)
fm.add_command(label="Save", command=savebutton_cb)
fm.add_separator()
#fm.add_command(label="Cancel Edit", command=pass)
fm.add_command(label="Exit", command=exitbutton_cb)
mb.add_cascade(label="File", menu=fm)

var1 = tk.StringVar(window)
var1.set(effectoption[0])

cr = ttk.Frame(window)
canvas = tk.Canvas(cr)
scrolling = ttk.Scrollbar(cr, orient="vertical", command=canvas.yview)

sw = window.winfo_screenwidth()
sh = window.winfo_screenheight()

Frm = tk.Frame(window, height=50, width=300)
Frm.pack(anchor=tk.N)

Frm2 = tk.Frame(window, height=25, width=100)
Frm2.pack(anchor=tk.NW)

#Frm3 = tk.Frame(window, height=50, width=500)
#Frm3.pack(anchor=tk.N)

#showWin = tk.Label(window, width=100, height=100)
#showWin.pack(side='left')

#showWin2 = tk.Label(window, width=100, height=100)
#showWin2.pack(side='left')

label = ttk.Label(
    window, text="Simple Image Photo Editing"
)

resetbutton = tk.Button(Frm, text="Reset", padx=0, pady=0, command=resetbutton_cb)
resetbutton.grid(row=0, column=1)

savebutton = tk.Button(Frm, text="Save", padx=0, pady=0, command=savebutton_cb)
savebutton.grid(row=0, column=2)

orima = None
editima = None


window.config(menu=mb)
cv2.waitKey(0)
tk.mainloop()


C:/Users/dean2/Downloads/maxresdefault.jpg
Original Dimensions :  (720, 1280, 3)
[[[124 122 104]
  [124 122 104]
  [124 122 104]
  ...
  [179 189 189]
  [179 189 189]
  [179 189 189]]

 [[124 122 104]
  [124 122 104]
  [124 122 104]
  ...
  [174 184 184]
  [174 184 184]
  [175 185 185]]

 [[124 122 104]
  [124 122 104]
  [124 122 104]
  ...
  [176 186 186]
  [176 186 186]
  [176 186 186]]

 ...

 [[ 93  89 108]
  [ 93  89 108]
  [ 94  90 109]
  ...
  [ 33  40  37]
  [ 32  41  38]
  [ 32  41  38]]

 [[ 92  90 109]
  [ 92  90 109]
  [ 94  90 109]
  ...
  [ 30  37  34]
  [ 28  37  34]
  [ 28  37  34]]

 [[ 92  90 109]
  [ 92  90 109]
  [ 94  90 109]
  ...
  [ 28  35  32]
  [ 26  35  32]
  [ 26  35  32]]]
[[[124 122 104]
  [124 122 104]
  [124 122 104]
  ...
  [179 189 189]
  [179 189 189]
  [179 189 189]]

 [[124 122 104]
  [124 122 104]
  [124 122 104]
  ...
  [174 184 184]
  [174 184 184]
  [175 185 185]]

 [[124 122 104]
  [124 122 104]
  [124 122 104]
  ...
  [176 186 186]
  [176 186 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\dean2\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "<ipython-input-1-b3aa01e8124d>", line 105, in insertbutton_cb
    orima = Label(image=image)
  File "C:\Users\dean2\anaconda3\lib\tkinter\__init__.py", line 3148, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "C:\Users\dean2\anaconda3\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
_tkinter.TclError: image "[[[104 122 124]
  [105 122 124]
  [106 121 124]
  ...
  [186 186 176]
  [187 187 177]
  [187 187 177]]

 [[104 122 124]
  [104 122 124]
  [106 121 124]
  ...
  [187 187 177]
  [188 188 178]
  [188 188 178]]

 [[104 122 124]
  [104 122 124]
  [104 122 124]
  ...
  [188 187 177]
  [189 187 178]
  [190 188 179]]

 ...

 [[107  88  92]
  [108  89  93]
  [108  89  93]
  ...
  [ 48  50  47]
  [ 48  50  45]
  [ 51  54  47]]

 [[108  89  93]
  [109  90  94]
  [109  90

257
0
0
261
0
0
264
0
0
267
0
0
270
0
0
275
0
0
280
0
0
283
0
0
288
0
0
291
0
0
295
0
0
300
0
0
301
0
0
304
0
0
306
0
0
308
0
0
311
0
0
312
0
0
314
0
0
317
0
0
321
0
0
322
0
0
325
0
0
327
0
0
330
0
0
332
0
0
334
0
0
335
0
0
337
0
0
338
0
0
340
0
0
343
0
0
345
0
0
346
0
0
348
0
0
350
0
0
353
0
0
355
0
0
356
0
0
358
0
0
359
0
0
361
0
0
359
0
0
358
0
0
356
0
0
355
0
0
353
0
0
351
0
0
348
0
0
346
0
0
343
0
0
340
0
0
337
0
0
332
0
0
330
0
0
327
0
0
324
0
0
319
0
0
314
0
0
312
0
0
308
0
0
304
0
0
303
0
0
300
0
0
298
0
0
295
0
0
293
0
0
290
0
0
288
0
0
283
0
0
280
0
0
275
0
0
269
0
0
257
0
0
253
0
0
246
0
0
241
0
0
235
0
0
225
0
0
222
0
0
217
0
0
209
0
0
204
0
0
199
0
0
198
0
0
194
0
0
191
0
0
188
0
0
185
0
0
181
0
0
178
0
0
175
0
0
170
0
0
167
0
0
162
0
0
159
0
0
154
0
0
149
0
0
146
0
0
144
0
0
142
0
0
141
0
0
139
0
0
136
0
0
134
0
0
131
0
0
128
0
0
125
0
0
123
0
0
121
0
0
118
0
0
115
0
0
112
0
0
110
0
0
107
0
0
104
0
0
100
0
0
99
0
0
96
0
0
92
0
0
91
0
0
89
0
0
87
0
0
86
0
0
84
0
0
83
0
0
7

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\dean2\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "<ipython-input-1-b3aa01e8124d>", line 105, in insertbutton_cb
    orima = Label(image=image)
  File "C:\Users\dean2\anaconda3\lib\tkinter\__init__.py", line 3148, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "C:\Users\dean2\anaconda3\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
_tkinter.TclError: image "[[[104 122 124]
  [105 122 124]
  [106 121 124]
  ...
  [186 186 176]
  [187 187 177]
  [187 187 177]]

 [[104 122 124]
  [104 122 124]
  [106 121 124]
  ...
  [187 187 177]
  [188 188 178]
  [188 188 178]]

 [[104 122 124]
  [104 122 124]
  [104 122 124]
  ...
  [188 187 177]
  [189 187 178]
  [190 188 179]]

 ...

 [[107  88  92]
  [108  89  93]
  [108  89  93]
  ...
  [ 48  50  47]
  [ 48  50  45]
  [ 51  54  47]]

 [[108  89  93]
  [109  90  94]
  [109  90

C:/Users/dean2/Downloads/maxresdefault.jpg
Original Dimensions :  (720, 1280, 3)
[[[124 122 104]
  [124 122 104]
  [124 122 104]
  ...
  [179 189 189]
  [179 189 189]
  [179 189 189]]

 [[124 122 104]
  [124 122 104]
  [124 122 104]
  ...
  [174 184 184]
  [174 184 184]
  [175 185 185]]

 [[124 122 104]
  [124 122 104]
  [124 122 104]
  ...
  [176 186 186]
  [176 186 186]
  [176 186 186]]

 ...

 [[ 93  89 108]
  [ 93  89 108]
  [ 94  90 109]
  ...
  [ 33  40  37]
  [ 32  41  38]
  [ 32  41  38]]

 [[ 92  90 109]
  [ 92  90 109]
  [ 94  90 109]
  ...
  [ 30  37  34]
  [ 28  37  34]
  [ 28  37  34]]

 [[ 92  90 109]
  [ 92  90 109]
  [ 94  90 109]
  ...
  [ 28  35  32]
  [ 26  35  32]
  [ 26  35  32]]]
[[[124 122 104]
  [124 122 104]
  [124 122 104]
  ...
  [179 189 189]
  [179 189 189]
  [179 189 189]]

 [[124 122 104]
  [124 122 104]
  [124 122 104]
  ...
  [174 184 184]
  [174 184 184]
  [175 185 185]]

 [[124 122 104]
  [124 122 104]
  [124 122 104]
  ...
  [176 186 186]
  [176 186 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\dean2\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "<ipython-input-1-b3aa01e8124d>", line 105, in insertbutton_cb
    orima = Label(image=image)
  File "C:\Users\dean2\anaconda3\lib\tkinter\__init__.py", line 3148, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "C:\Users\dean2\anaconda3\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
_tkinter.TclError: image "[[[104 122 124]
  [105 122 124]
  [106 121 124]
  ...
  [186 186 176]
  [187 187 177]
  [187 187 177]]

 [[104 122 124]
  [104 122 124]
  [106 121 124]
  ...
  [187 187 177]
  [188 188 178]
  [188 188 178]]

 [[104 122 124]
  [104 122 124]
  [104 122 124]
  ...
  [188 187 177]
  [189 187 178]
  [190 188 179]]

 ...

 [[107  88  92]
  [108  89  93]
  [108  89  93]
  ...
  [ 48  50  47]
  [ 48  50  45]
  [ 51  54  47]]

 [[108  89  93]
  [109  90  94]
  [109  90