In [ ]:
import tkinter as tk
from PIL import Image as PILImage
from PIL import ImageTk
from tkinter import Label
from tkinter import filedialog
from tkinter import ttk
from tkinter import Menu
import cv2
#import matplotlib.pyplot as plt
import numpy as np
 
WINDOW_NAME = "CV2 Photo Editor"
 
def on_change(effect):
    effect_choice = getattr(cv2, "COLOR_BGR2"+str(effect.split()[0]))
    edited = cv2.cvtColor(image, effect_choice)
    var1.set(effect)
    print(var1.get())
    print(effect)
def insertbutton_cb():
    #global orima, editima
    global image, edited
    global teste
 
    picpath = filedialog.askopenfilename(
        title="Select An Image",
        filetypes=(("JPG Files", "*.jpg"), ("GIF Files", "*.gif*"), ("PNG files", "*.png"), ("JPEG Files", "*.jpeg"))
    )
 
    if len(picpath) > 0:
        
        bright = 255
        contrast = 100
        
 
        image = cv2.imread(picpath)
        edited = cv2.imread(picpath)
 
        edited = np.array(edited)
        #edited = PILImage.fromarray(edited.astype('uint8'))
 
        print(picpath)
        print('Original Dimensions : ',image.shape)
        print(image)
        print(edited)
 
        scale_percent = 100 # percent of original size
        width = int(image.shape[1] * scale_percent / 100)
        height = int(image.shape[0] * scale_percent / 100)
        width2 = int(edited.shape[1] * scale_percent / 100)
        height2 = int(edited.shape[0] * scale_percent / 100)
        dim = (width, height)
        dim2 = (width2, height2)
 
        image = cv2.resize(image, dim, interpolation = cv2.INTER_AREA)
        edited = cv2.resize(edited, dim2, interpolation = cv2.INTER_AREA)
 
        #if effectoption[0] :
            #edited = cv2.cvtColor(edited, cv2.COLOR_BGR2RGB)
        #elif effectoption[1] :
            #edited = cv2.cvtColor(edited, cv2.COLOR_BGR2HSV)
        #elif effectoption[2] :
            #edited = cv2.cvtColor(edited, cv2.COLOR_BGR2LAB)
        #elif effectoption[3] :
            #edited = cv2.cvtColor(edited, cv2.COLOR_BGR2RGBA)
        #elif effectoption[4] :
            #edited = cv2.cvtColor(edited, cv2.COLOR_BGR2HLS)
 
        #on_change(image)
        #print(on_change(image))
        #edited = cv2.cvtColor(edited, cv2.COLOR_BGR2RGB)
 
        image =  PILImage.fromarray(image)
        edited = PILImage.fromarray(edited)
 
        #xa, ya, za = np.shape(image)
        #xb, yb, zb = np.shape(edited)
 
        #image = np.ones((xa, ya, za), np.uint8)
        #edited = np.ones((xb, yb, zb), np.uint8)
 
        image = np.uint8(image)
        edited = np.uint8(edited)
 
        #hueSlider = tk.Scale(Frm2, label="Hue",from_=0, to=100, orient=tk.HORIZONTAL, length=sw, resolution=1, command=huecb)
        #hueSlider.pack(anchor=tk.N)
 
        #saturationSlider = tk.Scale(Frm2, label="Saturation",from_=0, to=100, orient=tk.HORIZONTAL, length=sw, resolution=1, command=satcb)
        #saturationSlider.pack(anchor=tk.N)
 
        #brightSlider = tk.Scale(Frm2, label="Brightness",from_=0, to=100, orient=tk.HORIZONTAL, length=sw, resolution=1, command=brightcb)
        #brightSlider.pack(anchor=tk.N)
 
        #contrastSlider = tk.Scale(Frm2, label="Contrast",from_=0, to=100, orient=tk.HORIZONTAL, length=sw, resolution=1, command=contrastcb)
        #contrastSlider.pack(anchor=tk.N)

        #create trackbars for high,low H,S,V 
 
        cv2.namedWindow(WINDOW_NAME)
        cv2.createTrackbar('Bright', WINDOW_NAME, 255, 2 * 255, bccb)
        cv2.createTrackbar('Contrast', WINDOW_NAME, 255, 2 * 127, bccb)
        #ksize = 30

        cv2.createTrackbar('Median Blur', WINDOW_NAME, 0, 50, bccb)
        #functionbcs(edited, 0, 0, 0)
        bccb(0, 0)
        teste = controller(image, bright, contrast)
        cv2.imshow(WINDOW_NAME, teste)
 
        #cv2.waitKey(0)
    """
    if orima is None or editima is None:
        orima = Label(image=image)
        orima.image = image
        orima.pack(side="left", padx= 0, pady=0)
 
        editima = Label(image=edited)
        editima.image = edited
        editima.pack(side="right", padx= 0, pady=0)
    else:
        orima.configure(image=image)
        editima.configure(image=edited)
        orima.image = image
        editima.image = edited
    """
 
def resetbutton_cb():
    """
    orima = None
    editima = None
    """
    pass
 
def savebutton_cb():
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    edited = controller(image, bright, contrast)
    savepicpath = filedialog.asksaveasfilename(
        confirmoverwrite=False, defaultextension='.jpg', 
        filetypes=[("jpg files", '*.jpg'), ("png files", '*.png')],
        title="Choose filename"
    )
    saveimage =  cv2.imwrite(savepicpath, edited)
    print(saveimage)
    pass

def previewbutton_cb():
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    edited = controller(image, bright, contrast)
    cv2.imshow("Preview", edited)

def savebutton2_cb():
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    edited = controller(image, bright, contrast)
    edited = cv2.cvtColor(edited, cv2.COLOR_RGB2GRAY)
    savepicpath = filedialog.asksaveasfilename(
        confirmoverwrite=False, defaultextension='.jpg', 
        filetypes=[("jpg files", '*.jpg'), ("png files", '*.png')],
        title="Choose filename"
    )
    saveimage =  cv2.imwrite(savepicpath, edited)
    print(saveimage)
    pass

def previewbutton2_cb():
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    edited = controller(image, bright, contrast)
    edited = cv2.cvtColor(edited, cv2.COLOR_RGB2GRAY)
    cv2.imshow("Preview", edited)
def savebutton3_cb():
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    edited = controller(image, bright, contrast)
    kernel = np.array([[0.272, 0.534, 0.131],
                       [0.349, 0.686, 0.168],
                       [0.393, 0.769, 0.189]])
    
    edited = cv2.filter2D(image, -1, kernel)
    savepicpath = filedialog.asksaveasfilename(
        confirmoverwrite=False, defaultextension='.jpg', 
        filetypes=[("jpg files", '*.jpg'), ("png files", '*.png')],
        title="Choose filename"
    )
    saveimage =  cv2.imwrite(savepicpath, edited)
    print(saveimage)
    pass
def previewbutton3_cb():
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    edited = controller(image, bright, contrast)
    kernel = np.array([[0.272, 0.534, 0.131],
                       [0.349, 0.686, 0.168],
                       [0.393, 0.769, 0.189]])
    
    edited = cv2.filter2D(image, -1, kernel)
    cv2.imshow("Preview", edited)
    
def bccb(bright = 0, contrast=0):
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    #ksize = cv2.getTrackbarPos('Blur', WINDOW_NAME) 
    #print("Bl : " + str(ksize))
    edited = controller(image, bright, contrast)
    cv2.imshow(WINDOW_NAME, edited)
    
 
def controller(effect, bright=1, contrast=1):
    bright = int((bright - 0) * (255 - (-255)) / (510 - 0) + (-255))
 
    contrast = int((contrast - 0) * (127 - (-127)) / (254 - 0) + (-127))

    #effect = cv2.blur(effect, (ksize, ksize))
 
    if bright != 0:
        if bright > 0:
            shadow = bright
            max = 255
        else:
            shadow = 0
            max = 255 + bright
        alf = (max - shadow) / 255
        gam = shadow
 
        cal = cv2.addWeighted(effect, alf,
                              effect, 0, gam) # changed edited to effect, alfa to alf
    else:
        cal = effect
 
    if contrast != 0:
        Alf2 = float(131 * (contrast + 127)) / (127 * (131 - contrast))
        Gam2 = 127 * (1 - Alf2)
 
        # The function addWeighted calculates
        # the weighted sum of two arrays
        cal = cv2.addWeighted(cal, Alf2,
                              cal, 0, Gam2)
    #cv2.imshow('CV2 Photo Editor', effect)
    return cal

    
 
def exitbutton_cb():
    window.destroy()
    cv2.destroyAllWindows()
 
 
window = tk.Tk()
window.title('Simple Photo Editing')
mb = Menu(window)
#file manager
fm = Menu(mb, tearoff=0)
fm.add_command(label="Open", command=insertbutton_cb)
fm.add_command(label="Save", command=savebutton_cb)
fm.add_separator()
#fm.add_command(label="Cancel Edit", command=pass)
fm.add_command(label="Exit", command=exitbutton_cb)
mb.add_cascade(label="File", menu=fm)
 

 
cr = ttk.Frame(window)
canvas = tk.Canvas(cr)
scrolling = ttk.Scrollbar(cr, orient="vertical", command=canvas.yview)
 
sw = window.winfo_screenwidth()
sh = window.winfo_screenheight()
 
Frm = tk.Frame(window, height=50, width=300)
Frm.pack(anchor=tk.N)
 
Frm2 = tk.Frame(window, height=25, width=100)
Frm2.pack(anchor=tk.NW)
 
#Frm3 = tk.Frame(window, height=50, width=500)
#Frm3.pack(anchor=tk.N)
 
#showWin = tk.Label(window, width=100, height=100)
#showWin.pack(side='left')
 
#showWin2 = tk.Label(window, width=100, height=100)
#showWin2.pack(side='left')
 
label = ttk.Label(
    window, text="Simple Image Photo Editing"
)
 
resetbutton = tk.Button(Frm, text="Reset", padx=0, pady=0, command=resetbutton_cb)
resetbutton.grid(row=0, column=1)
 
savebutton = tk.Button(Frm, text="Save", padx=0, pady=0, command=savebutton_cb)
savebutton.grid(row=0, column=3)

previewbutton = tk.Button(Frm, text="Preview", padx=0, pady=0, command=previewbutton_cb)
previewbutton.grid(row=0, column=2)

previewgreybutton = tk.Button(Frm, text="Preview as Grayscale", padx=0, pady=0, command=previewbutton2_cb)
previewgreybutton.grid(row=1, column=1)
savegreybutton = tk.Button(Frm, text="Save as Grayscale", padx=0, pady=0, command=savebutton2_cb)
savegreybutton.grid(row=1, column=2)

previewgreybutton = tk.Button(Frm, text="Preview as Grayscale", padx=0, pady=0, command=previewbutton3_cb)
previewgreybutton.grid(row=2, column=1)
savegreybutton = tk.Button(Frm, text="Save as Grayscale", padx=0, pady=0, command=savebutton3_cb)
savegreybutton.grid(row=2, column=2)

orima = None
editima = None
 
window.config(menu=mb)
cv2.waitKey(0)
tk.mainloop()

C:/Users/dean2/Downloads/043517700_1562734690-54209311_851708111831566_1312904620044434127_n.jpg
Original Dimensions :  (853, 640, 3)
[[[146 155 165]
  [146 155 165]
  [146 155 165]
  ...
  [252 252 252]
  [251 251 251]
  [251 251 251]]

 [[146 155 165]
  [146 155 165]
  [146 155 165]
  ...
  [252 252 252]
  [251 251 251]
  [251 251 251]]

 [[146 155 165]
  [146 155 165]
  [146 155 165]
  ...
  [252 252 252]
  [251 251 251]
  [251 251 251]]

 ...

 [[106 125 163]
  [104 123 161]
  [102 121 159]
  ...
  [126 107 110]
  [122 103 106]
  [116  97 100]]

 [[109 128 166]
  [107 126 164]
  [105 124 162]
  ...
  [122 103 106]
  [118  99 102]
  [112  93  96]]

 [[113 132 170]
  [111 130 168]
  [109 128 166]
  ...
  [119 100 103]
  [115  96  99]
  [109  90  93]]]
[[[146 155 165]
  [146 155 165]
  [146 155 165]
  ...
  [252 252 252]
  [251 251 251]
  [251 251 251]]

 [[146 155 165]
  [146 155 165]
  [146 155 165]
  ...
  [252 252 252]
  [251 251 251]
  [251 251 251]]

 [[146 155 165]
  [146 155 1