In [25]:
import tkinter as tk
from PIL import Image as PILImage
from PIL import ImageTk
from tkinter import Label
from tkinter import filedialog
from tkinter import ttk
from tkinter import Menu
import cv2
#import matplotlib.pyplot as plt
import numpy as np
 
WINDOW_NAME = "CV2 Photo Editor"
 
def on_change(effect):
    effect_choice = getattr(cv2, "COLOR_BGR2"+str(effect.split()[0]))
    edited = cv2.cvtColor(image, effect_choice)
    var1.set(effect)
    print(var1.get())
    print(effect)
def insertbutton_cb():
    #global orima, editima
    global image, edited
    global teste
 
    picpath = filedialog.askopenfilename(
        title="Select An Image",
        filetypes=(("JPG Files", "*.jpg"), ("GIF Files", "*.gif*"), ("PNG files", "*.png"), ("JPEG Files", "*.jpeg"))
    )
 
    if len(picpath) > 0:
        
        bright = 255
        contrast = 100
        
 
        image = cv2.imread(picpath)
        edited = cv2.imread(picpath)
 
        edited = np.array(edited)
        #edited = PILImage.fromarray(edited.astype('uint8'))
 
        print(picpath)
        print('Original Dimensions : ',image.shape)
        print(image)
        print(edited)
 
        scale_percent = 100 # percent of original size
        width = int(image.shape[1] * scale_percent / 100)
        height = int(image.shape[0] * scale_percent / 100)
        width2 = int(edited.shape[1] * scale_percent / 100)
        height2 = int(edited.shape[0] * scale_percent / 100)
        dim = (width, height)
        dim2 = (width2, height2)
 
        image = cv2.resize(image, dim, interpolation = cv2.INTER_AREA)
        edited = cv2.resize(edited, dim2, interpolation = cv2.INTER_AREA)
 
        #if effectoption[0] :
            #edited = cv2.cvtColor(edited, cv2.COLOR_BGR2RGB)
        #elif effectoption[1] :
            #edited = cv2.cvtColor(edited, cv2.COLOR_BGR2HSV)
        #elif effectoption[2] :
            #edited = cv2.cvtColor(edited, cv2.COLOR_BGR2LAB)
        #elif effectoption[3] :
            #edited = cv2.cvtColor(edited, cv2.COLOR_BGR2RGBA)
        #elif effectoption[4] :
            #edited = cv2.cvtColor(edited, cv2.COLOR_BGR2HLS)
 
        #on_change(image)
        #print(on_change(image))
        #edited = cv2.cvtColor(edited, cv2.COLOR_BGR2RGB)
 
        image =  PILImage.fromarray(image)
        edited = PILImage.fromarray(edited)
 
        #xa, ya, za = np.shape(image)
        #xb, yb, zb = np.shape(edited)
 
        #image = np.ones((xa, ya, za), np.uint8)
        #edited = np.ones((xb, yb, zb), np.uint8)
 
        image = np.uint8(image)
        edited = np.uint8(edited)
  
 
        cv2.namedWindow(WINDOW_NAME)
        cv2.createTrackbar('Bright', WINDOW_NAME, 255, 2 * 255, bccb)
        cv2.createTrackbar('Contrast', WINDOW_NAME, 255, 2 * 127, bccb)
        #ksize = 30

        cv2.createTrackbar('Median Blur', WINDOW_NAME, 0, 50, bccb)
        #functionbcs(edited, 0, 0, 0)
        bccb(0, 0)
        teste = controller(image, bright, contrast)
        cv2.imshow(WINDOW_NAME, teste)
 
        #cv2.waitKey(0)
    """
    if orima is None or editima is None:
        orima = Label(image=image)
        orima.image = image
        orima.pack(side="left", padx= 0, pady=0)
 
        editima = Label(image=edited)
        editima.image = edited
        editima.pack(side="right", padx= 0, pady=0)
    else:
        orima.configure(image=image)
        editima.configure(image=edited)
        orima.image = image
        editima.image = edited
    """
 
def resetbutton_cb():
    """
    orima = None
    editima = None
    """
    pass
 
def savebutton_cb():
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    edited = controller(image, bright, contrast)
    savepicpath = filedialog.asksaveasfilename(
        confirmoverwrite=False, defaultextension='.jpg', 
        filetypes=[("jpg files", '*.jpg'), ("png files", '*.png')],
        title="Choose filename"
    )
    saveimage =  cv2.imwrite(savepicpath, edited)
    print(saveimage)
    pass

def previewbutton_cb():
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    edited = controller(image, bright, contrast)
    cv2.imshow("Preview", edited)

def savebutton2_cb():
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    edited = controller(image, bright, contrast)
    edited = cv2.cvtColor(edited, cv2.COLOR_RGB2GRAY)
    savepicpath = filedialog.asksaveasfilename(
        confirmoverwrite=False, defaultextension='.jpg', 
        filetypes=[("jpg files", '*.jpg'), ("png files", '*.png')],
        title="Choose filename"
    )
    saveimage =  cv2.imwrite(savepicpath, edited)
    print(saveimage)
    pass

def previewbutton2_cb():
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    edited = controller(image, bright, contrast)
    edited = cv2.cvtColor(edited, cv2.COLOR_RGB2GRAY)
    cv2.imshow("Preview", edited)
def savebutton3_cb():
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    edited = controller(image, bright, contrast)
    kernel = np.array([[0.272, 0.534, 0.131],
                       [0.349, 0.686, 0.168],
                       [0.393, 0.769, 0.189]])
    
    edited = cv2.filter2D(image, -1, kernel)
    savepicpath = filedialog.asksaveasfilename(
        confirmoverwrite=False, defaultextension='.jpg', 
        filetypes=[("jpg files", '*.jpg'), ("png files", '*.png')],
        title="Choose filename"
    )
    saveimage =  cv2.imwrite(savepicpath, edited)
    print(saveimage)
    pass
def previewbutton3_cb():
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    edited = controller(image, bright, contrast)
    kernel = np.array([[0.272, 0.534, 0.131],
                       [0.349, 0.686, 0.168],
                       [0.393, 0.769, 0.189]])
    
    edited = cv2.filter2D(image, -1, kernel)
    cv2.imshow("Preview", edited)
    
def bccb(bright = 0, contrast=0):
    bright = cv2.getTrackbarPos('Bright', WINDOW_NAME)
    print("B : " + str(bright))
    contrast = cv2.getTrackbarPos('Contrast', WINDOW_NAME)
    print("C : " + str(contrast))
    #ksize = cv2.getTrackbarPos('Blur', WINDOW_NAME) 
    #print("Bl : " + str(ksize))
    edited = controller(image, bright, contrast)
    cv2.imshow(WINDOW_NAME, edited)
    
 
def controller(effect, bright=1, contrast=1):
    bright = int((bright - 0) * (255 - (-255)) / (510 - 0) + (-255))
 
    contrast = int((contrast - 0) * (127 - (-127)) / (254 - 0) + (-127))

    #effect = cv2.blur(effect, (ksize, ksize))
 
    if bright != 0:
        if bright > 0:
            shadow = bright
            max = 255
        else:
            shadow = 0
            max = 255 + bright
        alf = (max - shadow) / 255
        gam = shadow
 
        cal = cv2.addWeighted(effect, alf,
                              effect, 0, gam) # changed edited to effect, alfa to alf
    else:
        cal = effect
 
    if contrast != 0:
        Alf2 = float(131 * (contrast + 127)) / (127 * (131 - contrast))
        Gam2 = 127 * (1 - Alf2)
 
        # The function addWeighted calculates
        # the weighted sum of two arrays
        cal = cv2.addWeighted(cal, Alf2,
                              cal, 0, Gam2)
    #cv2.imshow('CV2 Photo Editor', effect)
    return cal

    
 
def exitbutton_cb():
    window.destroy()
    cv2.destroyAllWindows()
 
 
window = tk.Tk()
window.title('Simple Photo Editing')
mb = Menu(window)
#file manager
fm = Menu(mb, tearoff=0)
fm.add_command(label="Open", command=insertbutton_cb)
fm.add_separator()
fm.add_command(label="Exit", command=exitbutton_cb)
mb.add_cascade(label="File", menu=fm)
pm = Menu(mb, tearoff=1)
pm.add_command(label="Preview RGB", command=previewbutton_cb)
pm.add_command(label="Preview Grayscale", command=previewbutton2_cb)
pm.add_separator()
pm.add_command(label="Preview Light Sepia", command=previewbutton3_cb)
mb.add_cascade(label="Preview", menu=pm)
sm = Menu(mb, tearoff=0)
sm.add_command(label="Save RGB", command=savebutton_cb)
sm.add_command(label="Save Grayscale", command=savebutton2_cb)
sm.add_separator()
sm.add_command(label="Save Light Sepia", command=savebutton3_cb)
mb.add_cascade(label="Save", menu=sm)
 

 
cr = ttk.Frame(window)
canvas = tk.Canvas(cr)
scrolling = ttk.Scrollbar(cr, orient="vertical", command=canvas.yview)
 
sw = window.winfo_screenwidth()
sh = window.winfo_screenheight()
 
Frm = tk.Frame(window, height=50, width=400)
Frm.pack(anchor=tk.N)
 
#Frm3 = tk.Frame(window, height=50, width=500)
#Frm3.pack(anchor=tk.N)
 
#showWin = tk.Label(window, width=100, height=100)
#showWin.pack(side='left')
 
#showWin2 = tk.Label(window, width=100, height=100)
#showWin2.pack(side='left')
 
label = ttk.Label(
    window, text="Simple Image Photo Editing"
)

apptitle = Label(window, 
                  text = "Simple Photo Editing by Dean and Erlangga")
apptitle.pack()

previewbutton = tk.Button(Frm, text="Open", padx=0, pady=0, command=insertbutton_cb)
previewbutton.grid(row=0, column=1)

previewbutton = tk.Button(Frm, text="Exit", padx=0, pady=0, command=exitbutton_cb)
previewbutton.grid(row=0, column=2)
 
savebutton = tk.Button(Frm, text="Save", padx=0, pady=0, command=savebutton_cb)
savebutton.grid(row=1, column=2)

previewbutton = tk.Button(Frm, text="Preview", padx=0, pady=0, command=previewbutton_cb)
previewbutton.grid(row=1, column=1)

previewgreybutton = tk.Button(Frm, text="Preview as Grayscale", padx=0, pady=0, command=previewbutton2_cb)
previewgreybutton.grid(row=2, column=1)
savegreybutton = tk.Button(Frm, text="Save as Grayscale", padx=0, pady=0, command=savebutton2_cb)
savegreybutton.grid(row=2, column=2)

previewgreybutton = tk.Button(Frm, text="Preview as Light Sepia", padx=0, pady=0, command=previewbutton3_cb)
previewgreybutton.grid(row=3, column=1)
savegreybutton = tk.Button(Frm, text="Save as Light Sepia", padx=0, pady=0, command=savebutton3_cb)
savegreybutton.grid(row=3, column=2)

orima = None
editima = None
 
window.config(menu=mb)
cv2.waitKey(0)
tk.mainloop()

C:/Users/dean2/Pictures/Ujicobaefekketiga.jpg
Original Dimensions :  (709, 472, 3)
[[[154 120 251]
  [150 117 251]
  [148 118 255]
  ...
  [119  88 255]
  [128  87 248]
  [152 103 255]]

 [[154 118 254]
  [152 119 254]
  [149 119 255]
  ...
  [119  87 255]
  [130  89 251]
  [152 105 255]]

 [[150 115 255]
  [152 117 255]
  [148 116 255]
  ...
  [117  85 255]
  [129  90 252]
  [152 106 255]]

 ...

 [[149  85  55]
  [165  97  68]
  [166  94  70]
  ...
  [  0   2 255]
  [  0   5 250]
  [ 12  15 243]]

 [[162  96  67]
  [175 108  81]
  [181 109  91]
  ...
  [  1   8 255]
  [  9  11 255]
  [ 21  23 248]]

 [[162  94  65]
  [172 105  80]
  [181 110  96]
  ...
  [  2   4 255]
  [  9   7 255]
  [ 22  22 246]]]
[[[154 120 251]
  [150 117 251]
  [148 118 255]
  ...
  [119  88 255]
  [128  87 248]
  [152 103 255]]

 [[154 118 254]
  [152 119 254]
  [149 119 255]
  ...
  [119  87 255]
  [130  89 251]
  [152 105 255]]

 [[150 115 255]
  [152 117 255]
  [148 116 255]
  ...
  [117  85 255]
  [129  9